controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

medicos:
    path: /medicos
    controller: App\Controller\MedicosController::buscarTodos
    methods:
        - GET
medico:
    path: /medico/{id}
    controller: App\Controller\MedicosController::buscarUm
    methods:
        - GET
remove_medico:
    path: /medico/{id}
    controller: App\Controller\MedicosController::remove
    methods:
        - DELETE
criar_medico:
    path: /medico
    controller: App\Controller\MedicosController::novo
    methods:
        - POST
atualizar_medico:
    path: /medico/{id}
    controller: App\Controller\MedicosController::atualizar
    methods:
        - PUT

especialidades:
    path: /especialidades
    controller: App\Controller\EspecialidadesController::buscarTodos
    methods:
        - GET
especialidade:
    path: /especialidade/{id}
    controller: App\Controller\EspecialidadesController::buscarUm
    methods:
        - GET
remove_especialidade:
    path: /especialidade/{id}
    controller: App\Controller\EspecialidadesController::remove
    methods:
        - DELETE
criar_especialidade:
    path: /especialidade
    controller: App\Controller\EspecialidadesController::novo
    methods:
        - POST
atualizar_especialidade:
    path: /especialidade/{id}
    controller: App\Controller\EspecialidadesController::atualizar
    methods:
        - PUT